import os
from dotenv import load_dotenv
import sys

if len(sys.argv) < 2:
    print("Usage: python config.py <env_file_path>")
    sys.exit(1)

env_file_path = sys.argv[1]
load_dotenv(env_file_path)
print("env:",env_file_path)


os.environ["TOKENIZERS_PARALLELISM"] = "false"

API_KEY=os.environ['API_KEY']
#aws-credentials
AWS_SERVICE=os.environ['AWS_SERVICE']
AWS_REGION_NAME=os.environ['AWS_REGION_NAME']
AWS_ACCESS_KEY_ID=os.environ['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY=os.environ['AWS_SECRET_ACCESS_KEY']
AWS_S3_BUCKET_NAME=os.environ['AWS_S3_BUCKET_NAME']
AWS_ERRORS_FOLDER=os.environ['AWS_ERRORS_FOLDER']
AWS_FILES_FOLDER=os.environ['AWS_FILES_FOLDER']

#mongodb-credentials
MONGODB_HOST=os.environ['MONGODB_HOST']
MONGODB_PORT=os.environ['MONGODB_PORT']
MONGODB_DATABASE_NAME=os.environ['MONGODB_DATABASE_NAME']
MONGODB_RESUME_DETAILS_COLLECTION_NAME=os.environ['MONGODB_RESUME_DETAILS_COLLECTION_NAME']
MONGODB_USER_DETAILS_COLLECTION_NAME=os.environ['MONGODB_USER_DETAILS_COLLECTION_NAME']
MONGODB_FILTER_WITH_SKILL_COLLECTION_NAME=os.environ['MONGODB_FILTER_WITH_SKILL_COLLECTION_NAME']
MONGODB_FEEDBACK_DETAIL_COLLECTION_NAME=os.environ['MONGODB_FEEDBACK_DETAIL_COLLECTION_NAME']
MONGODB_FEEDBACK_PROFILEQUEUES_COLLECTION_NAME=os.environ['MONGODB_FEEDBACK_PROFILEQUEUES_COLLECTION_NAME']
MONGODB_PREPARING_PROFILE_QUEUES_COLLECTION_FOR_TRAINING=os.environ['MONGODB_PREPARING_PROFILE_QUEUES_COLLECTION_FOR_TRAINING']

#resume-extensions
DOCX_EXTENSIONS=os.environ['DOCX_EXTENSIONS']
DOC_EXTENSIONS=os.environ['DOC_EXTENSIONS']
PDF_EXTENSIONS=os.environ['PDF_EXTENSIONS']
CSV_EXCEL_EXTENSIONS=os.environ['CSV_EXCEL_EXTENSIONS']
CSV_EXTENSIONS=os.environ['CSV_EXTENSIONS']
XLSX_EXTENSIONS=os.environ['XLSX_EXTENSIONS']

EMBEDDING_MODEL=os.environ['EMBEDDING_MODEL']
PINECONE_API_KEY=os.environ['PINECONE_API_KEY']
PINECONE_ENVIRONMENT=os.environ['PINECONE_ENVIRONMENT']
PINECONE_INDEX_NAME=os.environ['PINECONE_INDEX_NAME']

# #postgres credentials
# POSTGRES_HOST = os.environ['POSTGRES_HOST']
# POSTGRES_DATABASE= os.environ['POSTGRES_DATABASE']
# POSTGRES_USER = os.environ['POSTGRES_USER']
# POSTGRES_PASSWORD = os.environ['POSTGRES_PASSWORD']
# POSTGRES_PORT = os.environ['POSTGRES_PORT']
