param_names = [
    'firstName',
    'lastName',
    'email',
    'phone_no',
    'current_location',
    'present_address',
    'DateofBirth',
    'maritial_status',
    'recent_designation',
    'resume_organisation',
    'experience',
    'current_education',
    'qualification',
    'institute',
    'marks_in_percentage',
    'specialization',
    'year_of_passing',
    'resume_skill',
    'secondary_skills',
    'job_title',
    'description',
    'company_name',
    'company_location',
    'industry',
    'headline',
    'employment_type',
    'date_of_joining',
    'last_date',
    'current_ctc',
    'expected_ctc',
    'current_employment_status',
    'prefered_location',
    'ready_to_relocate',
    'overseas_experience',
    'notice_period',
    'having_passport',
    'passport_validity',
    'visa',
    'About',
]

# Define default values for all keys
default_values = {
    'First Name': '',
    'Last Name': '',
    'Email ID': '',
    'Mobile number': '',
    'Location': '',
    'Present Address': '',
    'Date of Birth': '',
    'Marital Status': '',
    'Designation': '',
    'Company': '',
    'Experience': '',
    'Education': '',
    'Qualification': '',
    'Education Institute': '',
    'Marks in percentage': '',
    'Specialization': '',
    'Year of passing': '',
    'Primary Skills': '',
    'Secondary Skills': '',
    'Job Title': '',
    'Job description': '',
    'Company Location': '',
    'Industry': '',
    'Headline': '',
    'Employment type': '',
    'Date of joining': '',
    'Last date': '',
    'Current CTC': 0,
    'Expected CTC': 0,
    'Current Employment Status': '',
    'Prefered Location': '',
    'Ready to relocate': False,
    'Overseas Experience': False,
    'Notice Period': 0,
    'Having Passport': False,
    'Passport Validity': '',
    'Visa': False,
    'About': ''
}